Repository Vonage-Community/tutorial-interactive_tutorials, pull requests merged in 2024-12, with the labels that each got.

#8 SMS - Node: update content + readme
  .github/workflows/workspace.yml
  tutorials/messages_api-node-sms/README.md
  tutorials/messages_api-node-sms/src/content/docs/03-initialize-client.md
  tutorials/messages_api-node-sms/src/content/docs/06-whats-next.md
  tutorials/messages_api-node-sms/src/content/docs/index.mdx
  tutorials/messages_api-node-sms/tutorial-config.json
Labels: Preview

#10 Adds toolbar app
  .github/workflows/toolbar.yml
  toolbar-app/README.md
  toolbar-app/astro.config.mjs
  toolbar-app/markdoc.config.mjs
  toolbar-app/package-lock.json
  toolbar-app/package.json
  toolbar-app/public/favicon.svg
  toolbar-app/src/assets/houston.webp
  toolbar-app/src/content/config.ts
  toolbar-app/src/content/docs/index.mdoc
  toolbar-app/src/env.d.ts
  toolbar-app/tsconfig.json
  toolbar-app/vonage-toolbar/README.md
  toolbar-app/vonage-toolbar/app.ts
  toolbar-app/vonage-toolbar/integration.ts
Labels: Toolbar

#9 Add Starter Tutorial
  .github/images/toolbar.png
  .github/workflows/workspace.yml
  README.md
  tutorials/00_Starter-Tutorial/.astro/astro/content.d.ts
  tutorials/00_Starter-Tutorial/.astro/settings.json
  tutorials/00_Starter-Tutorial/.astro/types.d.ts
  tutorials/00_Starter-Tutorial/README.md
  tutorials/00_Starter-Tutorial/astro.config.mjs
  tutorials/00_Starter-Tutorial/download-toolbar.js
  tutorials/00_Starter-Tutorial/markdoc.config.mjs
  tutorials/00_Starter-Tutorial/package.json
  tutorials/00_Starter-Tutorial/public/favicon.ico
  tutorials/00_Starter-Tutorial/src/content/config.ts
  tutorials/00_Starter-Tutorial/src/content/docs/01-welcome.md
  tutorials/00_Starter-Tutorial/src/content/docs/index.mdx
  tutorials/00_Starter-Tutorial/src/env.d.ts
  tutorials/00_Starter-Tutorial/tsconfig.json
Labels: Skip CI

#13 WIP sms with ruby
  tutorials/messages_api-ruby-sms/.astro/astro/content.d.ts
  tutorials/messages_api-ruby-sms/.astro/settings.json
  tutorials/messages_api-ruby-sms/.astro/types.d.ts
  tutorials/messages_api-ruby-sms/README.md
  tutorials/messages_api-ruby-sms/astro.config.mjs
  tutorials/messages_api-ruby-sms/download-toolbar.js
  tutorials/messages_api-ruby-sms/markdoc.config.mjs
  tutorials/messages_api-ruby-sms/package-lock.json
  tutorials/messages_api-ruby-sms/package.json
  tutorials/messages_api-ruby-sms/public/favicon.ico
  tutorials/messages_api-ruby-sms/src/content/config.ts
  tutorials/messages_api-ruby-sms/src/content/docs/01-welcome.md
  tutorials/messages_api-ruby-sms/src/content/docs/02-install-server-sdk.md
  tutorials/messages_api-ruby-sms/src/content/docs/03-initialize-client.md
  tutorials/messages_api-ruby-sms/src/content/docs/04-send-sms-code.md
  tutorials/messages_api-ruby-sms/src/content/docs/05-run-code.md
  tutorials/messages_api-ruby-sms/src/content/docs/06-whats-next.md
  tutorials/messages_api-ruby-sms/src/content/docs/index.mdx
  tutorials/messages_api-ruby-sms/src/env.d.ts
  tutorials/messages_api-ruby-sms/tsconfig.json
  tutorials/messages_api-ruby-sms/tutorial-config.json
  tutorials/messages_api-ruby-sms/vonage-toolbar/app.ts
  tutorials/messages_api-ruby-sms/vonage-toolbar/integration.ts
Labels: Preview
